# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - notebb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2821c2939fe64b9c8c6ca0ada6c15688 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_217da05f4ae841378652a435e38c459c }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2821c2939fe64b9c8c6ca0ada6c15688 }}/suraiya590/notesapibackend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'notebb'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ab6217974192413991d83e2b8a78fa0b }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2821c2939fe64b9c8c6ca0ada6c15688 }}/suraiya590/notesapibackend:${{ github.sha }}'